version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php
#      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fresh
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel
  admin:
    image: adminer
    networks:
      - laravel
    ports:
      - "8080:8080"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
#docker-compose run --rm composer require name_of_package
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  npm:
   image: node:erbium
   container_name: npm
   volumes:
     - ./src:/var/www/html
   entrypoint: ["npm"]
   working_dir: /var/www/html
   networks:
     - laravel

  artisan:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: artisan
   volumes:
     - ./src:/var/www/html
   depends_on:
    - mysql
   working_dir: /var/www/html
   entrypoint: ["/var/www/html/artisan"]
   networks:
    - laravel